include:
  - board: seeeduino_xiao_ble
    shield: totem_left 
  - board: seeeduino_xiao_ble
    shield: totem_right
  - board: seeeduino_xiao_ble
    shield: totem_dongle dongle_display


  
# there is no settingsreset (needed) for the XIAO
